# Generated by Django 4.0.4 on 2022-04-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Complete', 'Complete'), ('Pending', 'Pending')], default='Active', max_length=9)),
            ],
            options={
                'verbose_name_plural': 'Action Status',
            },
        ),
    ]
