# Generated by Django 4.0.4 on 2022-04-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('role', models.ManyToManyField(to='auction.role')),
            ],
        ),
    ]
