# Generated by Django 4.0.4 on 2022-04-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('role', models.ManyToManyField(to='auction.role')),
            ],
        ),
    ]
