# Generated by Django 4.0.4 on 2022-05-01 20:10

import auction.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_date', models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1897), auction.models.max_value_current_year])),
                ('publisher', models.CharField(max_length=200)),
                ('issue_number', models.IntegerField()),
                ('variant', models.BooleanField(default=False)),
                ('virgin_cover', models.BooleanField(default=False)),
                ('characters', models.CharField(blank=True, max_length=200, null=True)),
                ('choice', models.CharField(blank=True, choices=[('', '----'), ('Bronze Age', 'Bronze Age'), ('Copper Age', 'Copper Age'), ('Golden Age', 'Golden Age'), ('Modern Age', 'Modern Age'), ('Platinum Age', 'Platinum Age'), ('Silver Age', 'Silver Age')], max_length=12)),
                ('grade', models.CharField(blank=True, choices=[('', '----'), ('GM', 'GM'), ('M', 'M'), ('NM/M', 'NM/M'), ('NM+', 'NM+'), ('NM', 'NM'), ('NM-', 'NM-'), ('VF/NM', 'VF/NM'), ('VF+', 'VF+'), ('VF', 'VF'), ('VF-', 'VF-'), ('F/VF', 'F/VF'), ('F+', 'F+'), ('F', 'F'), ('F-', 'F-'), ('VG/F', 'VG/F'), ('VG+', 'VG+'), ('VG', 'VG'), ('VG-', 'VG-'), ('G/VG', 'G/VG'), ('G+', 'G+'), ('G', 'G'), ('G-', 'G-'), ('F/G', 'F/G'), ('F', 'F'), ('P', 'P')], max_length=5)),
                ('cover_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.image')),
            ],
        ),
    ]
