# Generated by Django 4.0.4 on 2022-05-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contributors', models.ManyToManyField(to='auction.contributor')),
                ('details', models.ManyToManyField(to='auction.detail')),
            ],
        ),
    ]
