# Generated by Django 4.0.4 on 2022-04-23 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='title',
        ),
    ]
