# Generated by Django 4.0.4 on 2022-04-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_update_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='characters',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='choice',
            field=models.CharField(blank=True, choices=[('', '----'), ('Bronze Age', 'Bronze Age'), ('Copper Age', 'Copper Age'), ('Golden Age', 'Golden Age'), ('Modern Age', 'Modern Age'), ('Platinum Age', 'Platinum Age'), ('Silver Age', 'Silver Age')], max_length=12, null=True),
        ),
    ]
